# Generated by Django 5.2.6 on 2025-11-01 15:56

import analytics_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0003_alter_uploadedfile_options_processeddata_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=analytics_app.models.get_upload_path, validators=[analytics_app.models.validate_file_size, analytics_app.models.validate_file_type]),
        ),
    ]
