# Generated by Django 5.2.6 on 2025-11-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0004_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='processed_chart_data',
            field=models.JSONField(default=dict),
        ),
    ]
