# Generated by Django 5.2.6 on 2025-11-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0005_uploadedfile_processed_chart_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='numeric_fields',
            field=models.JSONField(default=list),
        ),
    ]
