# Generated by Django 5.2.6 on 2025-11-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0006_uploadedfile_numeric_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='data_type',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='num_rows',
            field=models.BigIntegerField(default=0),
        ),
    ]
